### Register User

POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "firstname": "Vu",
  "lastname": "Trinh",
  "email":  "mail@mail.com",
  "password": "password",
  "role":  "ADMIN"
}

> {% client.global.set("auth-token", response.body.access_token); %}

### Create a new product

POST http://localhost:8080/api/v1/products
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
  "name": "Sample Product",
  "description": "A description of the product",
  "price": 49.99
}

### Query Products
GET http://localhost:8080/api/v1/products
Authorization: Bearer {{auth-token}}

### Update one product
POST http://localhost:8080/api/v1/products
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
  "id": 1,
  "name": "Updated Product",
  "description": "An updated description",
  "price": 59.99
}

### Query Products one more time

GET http://localhost:8080/api/v1/products
Authorization: Bearer {{auth-token}}